# Generated by Django 4.2.7 on 2024-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Список гостей'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Список бронювання'},
        ),
        migrations.AlterModelOptions(
            name='yogasession',
            options={'verbose_name': 'Заняття з йоги'},
        ),
        migrations.AlterModelManagers(
            name='guest',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('booked', 'Заброньовано'), ('cancelled', 'Скасовано')], default='booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='yogasession',
            name='session_type',
            field=models.CharField(choices=[('online', 'Онлайн-сесія'), ('offline', 'Офлайн-сесія')], default='group', max_length=200),
        ),
    ]
